-- AlterTable
ALTER TABLE `Comment` MODIFY `visibility` ENUM('ACTIVE', 'ARCHIVED', 'REJECTED') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Post` MODIFY `visibility` ENUM('ACTIVE', 'ARCHIVED', 'REJECTED') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `ProfileReaction` MODIFY `status` ENUM('ACTIVE', 'ARCHIVED', 'REJECTED') NOT NULL DEFAULT 'ACTIVE';
